SUBDIR+=	overview
SUBDIR+=	variables
SUBDIR+=	functions
#SUBDIR+=	debug
SUBDIR+=	conditionals
SUBDIR+=	containers
#SUBDIR+=	exceptions
SUBDIR+=	files
SUBDIR+=	classes
SUBDIR+=	recap
SUBDIR+=	graphics
SUBDIR+=	scipy
SUBDIR+=	project

INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
