SUBDIR+=	overview
SUBDIR+=	helloworld
SUBDIR+=	computational-thinking
SUBDIR+=	variables
#SUBDIR+=	functions
#SUBDIR+=	debug
SUBDIR+=	conditionals
SUBDIR+=	containers
#SUBDIR+=	exceptions
SUBDIR+=	classes
SUBDIR+=	files
#SUBDIR+=	recap
SUBDIR+=	graphics
#SUBDIR+=	scipy
SUBDIR+=	project

INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
