# The solution programs are tangled from ../contents.nw; this Makefile
# only cleans up the files they write when they run.  The data files
# madicken.txt, rövare.txt and bild.jpg are committed inputs and stay.
.PHONY: clean
clean:
	${RM} ordfrekvens.csv analys.csv filprov.txt prov.txt prov2.txt prov2.txt.tmp provkakor.txt
	${RM} -R __pycache__
