# The example programs are tangled from ../contents.nw; this Makefile only
# cleans up the files they write when they run.
.PHONY: clean
clean:
	${RM} test1.txt xy.txt xy.csv contacts.json
	${RM} -R __pycache__
